# Generated by Django 3.1 on 2020-09-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20200920_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inpatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BeneID', models.CharField(max_length=20, null=True)),
                ('ClaimID', models.CharField(max_length=20, null=True)),
                ('ClaimStartDt', models.DateField(null=True)),
                ('ClaimEndDt', models.DateField(null=True)),
                ('Provider', models.CharField(max_length=20, null=True)),
                ('InscClaimAmtReimbursed', models.IntegerField(null=True)),
                ('AttendingPhysician', models.CharField(max_length=20, null=True)),
                ('OperatingPhysician', models.CharField(max_length=20, null=True)),
                ('OtherPhysician', models.CharField(max_length=20, null=True)),
                ('AdmissionDt', models.DateField(null=True)),
                ('ClmAdmitDiagnosisCode', models.CharField(max_length=20, null=True)),
                ('DeductibleAmtPaid', models.IntegerField(null=True)),
                ('DischargeDt', models.DateField(null=True)),
                ('DiagnosisGroupCode', models.IntegerField(null=True)),
                ('ClmDiagnosisCode_1', models.CharField(max_length=20, null=True)),
                ('ClmDiagnosisCode_2', models.CharField(max_length=20, null=True)),
                ('ClmDiagnosisCode_3', models.CharField(max_length=20, null=True)),
                ('ClmDiagnosisCode_4', models.CharField(max_length=20, null=True)),
                ('ClmDiagnosisCode_5', models.CharField(max_length=20, null=True)),
                ('ClmDiagnosisCode_6', models.CharField(max_length=20, null=True)),
                ('ClmDiagnosisCode_7', models.CharField(max_length=20, null=True)),
                ('ClmDiagnosisCode_8', models.CharField(max_length=20, null=True)),
                ('ClmDiagnosisCode_9', models.CharField(max_length=20, null=True)),
                ('ClmDiagnosisCode_10', models.CharField(max_length=20, null=True)),
                ('ClmProcedureCode_1', models.CharField(max_length=20, null=True)),
                ('ClmProcedureCode_2', models.CharField(max_length=20, null=True)),
                ('ClmProcedureCode_3', models.CharField(max_length=20, null=True)),
                ('ClmProcedureCode_4', models.CharField(max_length=20, null=True)),
                ('ClmProcedureCode_5', models.CharField(max_length=20, null=True)),
                ('ClmProcedureCode_6', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
