# Generated by Django 3.1 on 2020-09-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_beneficiarytest_inpatienttest_outpatienttest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Provider', models.CharField(max_length=20, null=True)),
                ('PotentialFraud', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Provider', models.CharField(max_length=20, null=True)),
                ('PotentialFraud', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
