# Generated by Django 3.1 on 2020-09-21 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_test_train'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='PotentialFraud',
        ),
    ]
